target_col:   #added
  - "target"    #added
categorical_features:
  - "sex"
  - "cp"
  - "fbs"  #added
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
numerical_features:
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"  #added
  - "oldpeak"
features_to_drop:
  - "fbs"